services:
  - type: web
    name: mi-fastapi-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://terapia_user:terapia_2025@valoracioneschats.tvsnake.mongodb.net/Conversaciones_test?retryWrites=true&w=majority&appName=ValoracionesChats
